<?php
$i=0;
foreach ($this->topExp as $keyT => $valueT) {
	foreach ($this->allCitys as $keyC => $valueC) {
		if ($keyT == $valueC['id']) {
			$topCountrys[$i]=$valueC['country_id'];
			$i++;
		}
	}
}
$topCountrys=array_unique($topCountrys);
?>

<div class="container">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
<?php
$i=0;
foreach ($topCountrys as $keyT => $valueT) {
	foreach ($this->allCountries as $keyC => $valueC) {
		if ($valueT == $valueC['id']) {
			if ($i==0) {
				echo '<div class="item active">
				      <img src="'.$valueC['image'].'" height="560px" width="1260px">
							<div class="carousel-caption">
						    <h3>'.$valueC['country_name'].'</h3>
								<a class="btn btn-default" href="/country/displaycities/coid/'.$valueC['id'].'" role="button">Visit</a>
						  </div>
				    </div>';
				$i++;
			}
			else {
				echo '<div class="item">
				      <img src="'.$valueC['image'].'" height="560px" width="1260px">
							<div class="carousel-caption">
						    <h3>'.$valueC['country_name'].'</h3>
								<a class="btn btn-default" href="/country/displaycities/coid/'.$valueC['id'].'" role="button">Visit</a>
						  </div>
				    </div>';
			$i++;
			}
			break;
		}
	}
	if ($i==6) {
		break;
	}
}
?>
</div>
<!-- Controls -->
<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	<span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	<span class="sr-only">Next</span>
</a>
</div>
</div>

<br>
<br>
<br>


<!--Grid -->
<div class="container">
<div class="row">
	<?php
	$i=0;
	foreach ($this->topExp as $keyT => $valueT) {
		foreach ($this->allCitys as $keyC => $valueC) {
			if ($keyT == $valueC['id']) {
				echo '  <div class="col-lg-4 col-md-6 col-sm-12">
				    <div class="thumbnail">
				      <img src="'.$valueC['photo'].'" class="img-circle">
				      <div class="caption">
				        <h3 class="text-center">'.$valueC['city_name'].'</h3>
				        <p class="text-center"><a href="/country/city/cid/'.$valueC['id'].'" class="btn btn-primary" role="button">View City</a></p>
				      </div>
				    </div>
				  </div>';
					$i++;
			}
			if ($i==6) {
				break;
			}
		}
	}
?>

</div>
</div>
