<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.
min.css" integrity="sha384-
1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-
theme.min.css" integrity="sha384-
fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
crossorigin="anonymous"></script>
</head>
<title>Zend Project</title>


<?php
$auth=Zend_Auth::getInstance();
$storage=$auth->getStorage();
$userData=$storage->read();
if (empty($userData)) {
  echo '<a href="/admin/login">Log in as admin</a>';
}
else {
  // echo '<a href="/user/logout">Logout <span class="sr-only">(current)</span></a>';
}
 ?>




<?php echo $this->layout()->content; ?>
<div style ="background:black;">
<hr>
<center >
   <h3 bgcolor="white">Copyright &copy;2017 opensource</h3>
</center>
<hr>
</div>
