<html>
    <head>
        <title>Zend Project</title>
        <!-- Latest compiled and minified CSS -->

         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

         <!-- jQuery library -->

         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

         <!-- Latest compiled JavaScript -->

         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


        <?php echo $this->headMeta(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle . PHP_EOL;
        echo $this->jQuery() . PHP_EOL;
        ?>
        <?php
            echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.css');
            echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');
            echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/datepicker.js');
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">OS Alex</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/admin/user-list">Home <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact Us</a></li>
  <!--********************** destnation in navbar *****************************  -->
                      <!-- <li>
                        <select onChange="window.location.href=this.value"  >
                          <option value="#" >Destnation</option>
                        <?php
                        // $country_model=new Application_Model_Country();
                        // $all=$country_model->allCountries();
                        // foreach($all as $key => $value)
                    		// {
                        //   // echo $this->formSelect('test', 'Option 1');
                        //   // echo  "<li><a href='#'></a></li>";
                        //   echo "<option value='/country/displaycities/coid/".$value['id']."'>".$value['country_name']."</option>";
                        // }
                        ?>
                      </select>
                    </li> -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Destnation<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <?php
                          $country_model=new Application_Model_Country();
                          $all=$country_model->allCountries();
                          foreach($all as $key => $value)
                      		{

                        ?>
                        <li><a href="/country/displaycities/coid/<?= $value['id']?>"><?= $value['country_name']?></a></li>
                        <?php

                          }
                          ?>

                          </ul>
                        </li>
                    </ul>
<!--************************* login with facebook layout***************-->
                    <?php
  $authAdapter = Zend_Auth::getInstance();
  $storage=$authAdapter->getStorage();
  $userData=$storage->read();
  $identity = $authAdapter->getIdentity();
  $fbsession= new Zend_Session_Namespace('facebook');

  if (!empty($userData))
    {
      $name = $userData->user_name;
      echo '<li class="active" style="color:white;margin-right:30px;margin-top:10px;font-size:20px;"> Welcome '. $name. '</li>';
      echo '<li class="active"><a href="/admin/logout"> Logout<span class="sr-only">(current)</span></a></li>';
    ?>

<?php
    }
    elseif ($fbsession->fname)
    {
      echo '<li class="active" style="color:white;margin-right:30px;margin-top:10px;font-size:20px;"> Welcome '. $fbsession->fname. '</li>';
      echo '<li class="active"><a href="/admin/logout"> Logout<span class="sr-only">(current)</span></a></li>';
    ?>

<?php
    }
  //   else {
  //   echo '<li class="active"><a href="/admin/login">Login<span class="sr-only">(current)</span></a></li>';
  // }
?>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <?php
        // $auth=Zend_Auth::getInstance();
        // $storage=$auth->getStorage();
        // $userData=$storage->read();
        // if (empty($userData)) {
        //     echo '<a href="/admin/login">Log in as admin</a>';
        // }
        // else {
        //      echo '<a href="/user/logout">Logout <span class="sr-only">(current)</span></a>';
        // }
        ?>
        <?php echo $this->layout()->content; ?>

        <div style ="background:black;">
            <hr>
            <center >
                <h3 bgcolor="white">Copyright &copy;2017 opensource</h3>
            </center>
            <hr>
        </div>
    </body>
</html>
