 <aside class="main-sidebar" style="position: fixed">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>e7na k adminssssss fen nfsna</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
       


<li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="/user/home">
            <span>Home</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>

       <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#users">
            <span>Users</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>
       <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#hotels">
            <span>Hotels</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>
 <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#sights">
            <span>Locations</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>

          <!-- <ul class="treeview-menu">
            <li><a href="/admin/add-hotel"><i class="fa fa-circle-o"></i> add Hotel</a></li>
            <li class="active"><a href="/admin/list-hotel"><i class="fa fa-circle-o"></i> Delete Hotel</a></li>
            <li><a href="/admin/update-hotel"><i class="fa fa-circle-o"></i>Update Hotel Data</a></li>
            <li class="active"><a href="/admin/list-hotel"><i class="fa fa-circle-o"></i>List Hotels</a></li>
          </ul> -->
        
        <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#city">
            <span >Cities</span>
            <span class="pull-right-container">
            </span>
          </a>
          <!-- <ul class="treeview-menu">
            <li><a href="/admin/add-city"><i class="fa fa-circle-o"></i> Add City</a></li>
            <li><a href="/admin/list-city"><i class="fa fa-circle-o"></i> Delete City</a></li>
            <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> show all Cities</a></li>
          </ul> -->
        </li>

        <li class="treeview">
          <a href="#country">
            <i class="fa fa-th"></i> <span>Countries</span>
            <span class="pull-right-container">
            </span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">






<div id="view-content">

<?php 

echo $this->city_form;

?>


</div>