
<html>
<head>
  <!-- <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
   --><title>Travel Intake 37 OpenSource</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="plugins/jvectormap/jquery-jvectormap-1.2.2.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="dist/css/skins/_all-skins.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">

    <!-- Logo -->
    <a href="index.html" class="logo" style="top:0px; position: fixed" >
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" style="top:0px; position: fixed; width:1090px" >
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            
            <ul class="dropdown-menu">
              <li>
                <!-- inner menu: contains the actual data -->
               
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
         
          <!-- Tasks: style can be found in dropdown.less -->
          
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
            
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>

    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar" style="position: fixed">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>e7na k adminssssss fen nfsna</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
       


<li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="/user/home">
            <span>Home</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>

       <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#users">
            <span>Users</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>
       <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#hotels">
            <span>Hotels</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>
 <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#sights">
            <span>Locations</span>
            <span class="pull-right-container">
            </span>
          </a>
          </li>

          <!-- <ul class="treeview-menu">
            <li><a href="/admin/add-hotel"><i class="fa fa-circle-o"></i> add Hotel</a></li>
            <li class="active"><a href="/admin/list-hotel"><i class="fa fa-circle-o"></i> Delete Hotel</a></li>
            <li><a href="/admin/update-hotel"><i class="fa fa-circle-o"></i>Update Hotel Data</a></li>
            <li class="active"><a href="/admin/list-hotel"><i class="fa fa-circle-o"></i>List Hotels</a></li>
          </ul> -->
        
        <li class="treeview">
            <i class="fa fa-files-o"></i>
            <a href="#city">
            <span >Cities</span>
            <span class="pull-right-container">
            </span>
          </a>
          <!-- <ul class="treeview-menu">
            <li><a href="/admin/add-city"><i class="fa fa-circle-o"></i> Add City</a></li>
            <li><a href="/admin/list-city"><i class="fa fa-circle-o"></i> Delete City</a></li>
            <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> show all Cities</a></li>
          </ul> -->
        </li>

        <li class="treeview">
          <a href="#country">
            <i class="fa fa-th"></i> <span>Countries</span>
            <span class="pull-right-container">
            </span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      
      <!-- /.row -->

      <!-- /.row -->

      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <div class="col-md-8">
          <!-- MAP & BOX PANE -->
     
          <!-- /.box -->
        
          <!-- /.row -->

          <!-- TABLE: LATEST ORDERS -->
<div id="users" class="box box-info">
          
            <div class="box-header with-border">

<table class="table table-bordered table-striped">
  <th>Name</th><th colspan="3">Actions</th>

<?php
foreach ($this->all_users as $key => $value) {
  echo "<tr><td>".$value['user_name']."</td>";
  echo "<td><a class='btn btn-info' href='/admin/user-details/uid/".$value['id']."'>Details</a></td>";
  if ($value['type']=='blocked') {
    echo "<td><a class='btn btn-warning' href='/admin/user-unblock/uid/".$value['id']."'>Un Block</a></td>";
  }
  elseif ($value['type']=='normal') {
    echo "<td><a class='btn btn-danger' href='/admin/user-block/uid/".$value['id']."'>Block</a></td>";
  }
  if ($value['type']=='normal') {
    echo "<td><a class='btn btn-warning' href='/admin/user-asadmin/uid/".$value['id']."'>Make Admin</a></td> </tr>";
  }
}
 ?>
</table>
<hr>
<?php
echo $this->track_form;
?>

</div></div>



 <div id="sights" class="box box-info">
          
            <div class="box-header with-border">

    <table class='table table-striped'>
        <tr>
            <th>Sight Name</th>
            <th>City</th>
            <th colspan='2'>Details</th>
        </tr>
        <?php
        foreach($this->allSights as $key => $value)
        {
            echo "<tr>
              <td>".$value['sight_name']."</td>
              <td><a class='btn btn-success' href='/admin/sightdetails/sightid/".$value['id']."'> Details </a></td>
              <td><a class='btn btn-primary' href='/admin/editsight/sightid/".$value['id']."'> Edit </a></td>
              <td> <a class='btn btn-danger' href='/admin/deletesight/sightid/".$value['id']."'> Delete </a> </td>
            </tr>";
        }
        ?>
    </table>
      <a class='btn btn-info' href='/admin/addsight'> Add Sight </a>

</div>
          </div>
 <div id="country" class="box box-info">
          
            <div  class="box-header with-border">
            <table class="table table-bordered">
    <tr>
    <!-- <th class="panel-heading">ID</th> -->
    <th>Country Name</th>
    <th colspan="2">Action</th>
    </tr>
  <?php
    foreach($this->countries as $key => $value)
    {
      echo "<tr>".  //<td>". $value['id']."</td>" .
      "<td>". $value['country_name'] . "</td>" .
      // "<td> <a class='btn btn-info' href='add/cid/".$value['id']."'> Add </a>".
      "<td> <a class='btn btn-danger' href='/admin/deletecountry/cid/".$value['id']."'> Delete </a>".
      "<td> <a class='btn btn-success' href='/admin/updatecountry/cid/".$value['id']."'> Update </a>".
      "</tr>";
    }

  ?>

  
  </table>
 
  <a class='btn btn-info' href='/admin/addcountry'> Add Country </a>
            </div>
            </div>


 <div id="city" class="box box-info">
          
            <div  class="box-header with-border">

            <table class="table table-striped">
  
  <tr>
  
  <th>city Name</th>
  
  <th>Action</th>

  </tr>
  <?php

  
  foreach ($this->city as $key => $value) {
    # code...
  
  echo "<tr>
  <td>".$value['city_name']."</td>".
  "<td> <a class='btn btn-info' href='/admin/city-details/uid/".$value['id']."'> Details </a></td>".
  "<td> <a class='btn btn-success' href='/admin/city-Update/uid/".$value['id']."'> Update </a></td>".
  "<td> <a class='btn btn-danger' href='/admin/delete-city/uid/".$value['id']."'> Delete </a></td>
  

  </tr>";
}
  ?>

</table>
<a class="btn btn-info" href='/admin/add-city'>create New City</a>
            </div>
            </div>




          <div id="hotels" class="box box-info">

            <div  class="box-header with-border">
              <h3 class="box-title">Latest Hotel</h3>


  <table class="table table-striped">
  
  <tr>
  <th>Hotel Name</th>
  <th>Action</th>

  </tr>
  <?php

  // echo $this->hotel;
  // die();
  foreach ($this->hotel as $key => $value) {
    # code...
  
  echo "<tr>
  
  <td>".$value['hotel_name']."</td>".
  "<td> <a class='btn btn-info' href='/admin/hotel-details/uid/".$value['id']."'> Details </a></td>".
  "<td> <a class='btn btn-success' href='/admin/Update-hotel/uid/".$value['id']."'> Update </a></td>".
  "<td> <a class='btn btn-danger' href='/admin/delete-hotel/uid/".$value['id']."'> Delete </a></td>
  

  </tr>";
}
  ?>

</table>
  <a class="btn btn-info" href='/admin/add-hotel'>create New Hotel</a>


              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>

            <!-- /.box-header -->
          
            <!-- /.box-body -->
          
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->

      
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.8
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark" >
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->

      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="bootstrap/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/app.min.js"></script>
<!-- Sparkline -->
<script src="plugins/sparkline/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll 1.3.0 -->
<script src="plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- ChartJS 1.0.1 -->
<script src="plugins/chartjs/Chart.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard2.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>
</body>
</html>