
<div class="container">
    <div class="jumbotron">
        <?php
        extract($this->sightData);
        echo "<h1>".$sight_name."</h1>";
        echo "<div class='panel panel-primary'>
							  <div class='panel-heading'>
							    <h3 class='panel-title'>".$sight_name." </h3>
							  </div>
							  <div class='panel-body'>
							    <h3>$city_id</h3>
							  </div>
						</div>";
        ?>
    </div>
</div>
