
<div class="container">
    <div class="jumbotron">
        <?php
        extract($this->sightData);
        echo "<div class='panel panel-primary'>
							  <div class='panel-heading'>
							   <h1 style='align:center'>location </h>
							  </div>
							  <div class='panel-body'>
					   <h4><b>SightName :</b>".$sight_name." </h4>

							    <h4><b>City Name :</b>".$this->cityName."</h4>
							  </div>
						</div>";
        ?>
    </div>
</div>
