<div class="container">

<div class="panel panel-info">
  <div class="panel-heading">
    <center>
    <h2 class="panel-title">Index Page</h2>
  </center>
  </div>

<div class="panel-body">
<table class="table table-bordered table-striped">
  <th>Name</th><th colspan="3">Actions</th>

<?php
foreach ($this->all_users as $key => $value) {
  echo "<tr><td>".$value['user_name']."</td>";
	echo "<td><a class='btn btn-info' href='/admin/user-details/uid/".$value['id']."'>Details</a></td>";
	if ($value['type']=='blocked') {
		echo "<td><a class='btn btn-warning' href='/admin/user-unblock/uid/".$value['id']."'>Un Block</a></td>";
	}
	elseif ($value['type']=='normal') {
		echo "<td><a class='btn btn-danger' href='/admin/user-block/uid/".$value['id']."'>Block</a></td>";
	}
  if ($value['type']=='normal') {
    echo "<td><a class='btn btn-warning' href='/admin/user-asadmin/uid/".$value['id']."'>Make Admin</a></td> </tr>";
  }
}
 ?>
</table>
<hr>
<?php
echo $this->track_form;
?>
</div>
</div>

</div>
