<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
		<h1><center>
		<?php
			echo $this->user_data['user_name'];
		?>
		</center></h1>
	</div>

<div class="panel-body" border="1">
  <img src="<?php echo $this->user_data['image']?>" alt="no image" height='140' width='140' class="img-rounded center-block">
	<h4> Email : <?php echo $this->user_data['email'] ?> </h4>
  <h4> Type : <?php echo $this->user_data['type'] ?> </h4>
</div>
</div>

</div>
