<!DOCTYPE html>
<html>
<head>
	<title>Admin Country Page</title>
</head>
<body>
<div class="container">
	<div class="panel panel-info">
	<div class="panel-heading">
		<?php
		$country= new Application_Model_Country();
		$data=$country->getCountryData($this->co_id); ?>
		<h1><center>	<?php echo $data['country_name'] ?>	</h1></center>

	</div>
	<table class="table table-bordered">
		<tr>
		<!-- <th class="panel-heading">ID</th> -->
		<th>Cities Names</th>

		</tr>
	<?php
	echo '<img src="'.$data['image'].'" alt="no image" height="250" width="500" class="img-rounded center-block">';
		 foreach($this->cities as $key => $value)
		 {
			 echo "<tr><td>". $value['city_name'] ."</td></tr>";
			// print_r($this->cities);

		 }

	?>

	</div>
	</table>

  </div>
	<div id="googleMap" style="width:100%;height:400px;"></div>

<script>
function myMap() {
var mapProp= {
    center:new google.maps.LatLng(51.508742,-0.120850),
    zoom:5,
};
var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6iNsWl82aNiwAI2oXTXksCF7QtrWACEI&callback=myMap"></script>
	<a class='btn btn-info' href='/country/showcountries'> Back </a>
	</body>
	</html>
