<!DOCTYPE html>
<html>
<head>
	<title>Admin Country Page</title>
</head>
<body>
<div class="container">
	<div class="panel panel-info">
	<div class="panel-heading">
		<?php
		$country= new Application_Model_Country();
		$data=$country->getCountryData($this->co_id); ?>
		<h1><center>	<?php echo $data['country_name'] ?>	</h1></center>

	</div>
	<table class="table table-bordered">
		<tr>
		<!-- <th class="panel-heading">ID</th> -->
		<th>Cities Names</th>

		</tr>
	<?php
	echo '<img src="'.$data['image'].'" alt="no image" height="250" width="500" class="img-rounded center-block">';
		 foreach($this->cities as $key => $value)
		 {
			 echo "<tr><td><a href='/country/city/cid/".$value['id']."'>". $value['city_name'] ."</a></td></tr>";
			// print_r($this->cities);

		 }

	?>

	</div>
	</table>

  </div>
	<a class='btn btn-info' href='/country/showcountries'> Back </a>
	</body>
	</html>
