<!DOCTYPE html>
<html>
<head>
	<title> Country Page</title>
</head>
<body>
<div class="container">
	<div class="panel panel-info">
	<div class="panel-heading">
		<h1><center>Countries</h1></center>

	</div>
	<table class="table table-bordered">
		<tr>
		<!-- <th class="panel-heading">ID</th> -->
		<th>Countries Names</th>
		<!-- <th colspan="2">Action</th> -->
		</tr>
	<?php
		foreach($this->countries as $key => $value)
		{
			echo "<tr>".  //<td>". $value['id']."</td>" .
			"<td><a class='' href='/country/displaycities/coid/".$value['id']."'> ".$value['country_name']."</a></td>".
			"</tr>";
		}

	?>

	</div>
	</table>
  </div>

	</body>
	</html>
