<!DOCTYPE html>
<html>
<head>
	<title>Edit Profile</title>
</head>
<body>
<table>
	<div class="container">
	<div class="panel panel-primary">
  	<!-- <div class="panel-heading">
    <h1><center>Add Country </center></h1>
  </div> -->
  <div class="panel-body">
  <?php
	// echo $this->uid;
  	echo $this->signup_form;
  ?>
 </div>
</div>
<a class='btn btn-info' href='/visitor/profile'> Back to Profile </a>
</div>
</table>
</body>
</html>
