
<!-- <div>
	foreach($this->experience as $key=$value){

	} -->

<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
		<h1><center>
		<?php
			echo $this->user_data['user_name'];
		?>
		</center></h1>
	</div>

<div class="panel-body" border="1">
  <img src="<?php echo $this->experience['image']?>" alt="no image" height='140' width='140' class="img-rounded center-block">
	<h4> title : <?php echo $this->experience['title'] ?> </h4>
  <h4> Description : <?php echo $this->experience['description'] ?> </h4>
</div>
</div>

</div>
